#pragma once
#include <WinUser.h>

enum CustomWinMsg
{
	WM_UI_CUSTOM = WM_USER + 2120,
	WM_ON_LOGIN,
	WM_ON_LOGOUT,
	WM_ON_START_CONTEXT,
	WM_ON_STOP_CONTEXT,
	WM_ON_ENTER_ROOM,
	WM_ON_EXIT_ROOM,
	WM_ON_ENDPOINTS_UPDATE_INFO,
	WM_ON_REQUEST_VIEW_LIST,
	WM_ON_CANCEL_ALL_VIEW,

	WM_ON_MIC_OPERATION,
	WM_ON_PLAYER_OPERATION,
	WM_ON_SCREEN_SHARE_SEND_OPERATION,
	WM_ON_ACCOMPANY_OPERATION,
	WM_ON_CAMERA_OPERATION,
    WM_ON_CAMERA_CHANGE,
	WM_ENDPOINT_MENU_ITEM,
	WM_ON_AUDIO_DEVICE_DETECT,

	WM_ON_START_DEVICE_TEST,
	WM_ON_STOP_DEVICE_TEST,
	WM_ON_DEVICE_TEST_MIC_OPERATION,
	WM_ON_DEVICE_TEST_PLAYER_OPERATION,
	WM_ON_DEVICE_TEST_CAMERA_OPERATION,
    WM_ON_DEVICE_TEST_CAMERA_DETECT_OPERATION,

	WM_ON_PUSH_VIDEO_START,
	WM_ON_PUSH_VIDEO_STOP,
	WM_ON_RECORD_VIDEO_START,
	WM_ON_RECORD_VIDEO_STOP,

	WM_TEST_UI_MSG,
	WM_CHANNEL_MSG,
};




